group = 'com.evento'
version = '2.4.3'

allprojects {
    ext {
        javaLanguageVersion = JavaLanguageVersion.of(25)
        eventoVersion = '2.4.3'
        jacksonVersion = '2.22.1'
        nettyVersion = '4.2.16.Final'
        lz4Version = '1.8.0'
        micrometerVersion = '1.13.6'
        junitVersion = '5.11.4'
        assertjVersion = '3.27.7'
        lombokVersion = '1.18.46'
        flywayVersion = '13.0.0'
        testcontainersVersion = '1.21.3'
        postgresJdbcVersion = '42.7.13'
        mysqlJdbcVersion = '26.7.0'
        hikariVersion = '7.1.0'
        jazzerVersion = '0.30.0'
    }
}

subprojects {
    apply plugin: 'java'
    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(25)
        }
    }
}