evento.server.host=localhost
evento.server.port=3030
evento.bundle.id=lab-ms-command
evento.bundle.version=1
# evento.bundle.repository-url=https://github.com/org/repo/blob/main/evento-lab-microservices/evento-lab-ms-command
# evento.bundle.line-prefix=L
