POST http://localhost:9001/api/demo/
Content-Type: application/json

{
  "demoId": "001",
  "name": "aaa",
  "value": 5
}
###
GET http://localhost:9001/api/demo/?page=0
Content-Type: application/json
###
GET http://localhost:9001/api/demo/001
Content-Type: application/json
###
POST http://localhost:9001/api/demo/
Content-Type: application/json

{
  "demoId": "002",
  "name": "aaa",
  "value": 5
}
###
POST http://localhost:9001/api/demo/
Content-Type: application/json

{
  "demoId": "003",
  "name": "aaa",
  "value": 5
}
###
POST http://localhost:9001/api/demo/
Content-Type: application/json

{
  "demoId": "004",
  "name": "aaa",
  "value": 5
}
###
POST http://localhost:9001/api/demo/
Content-Type: application/json

{
  "demoId": "005",
  "name": "aaa",
  "value": 5
}
###
PUT http://localhost:9001/api/demo/001
Content-Type: application/json

{
  "demoId": "001",
  "name": "aaa",
  "value": 9
}
###

PUT http://localhost:9001/api/demo/002
Content-Type: application/json

{
  "demoId": "001",
  "name": "aaa",
  "value": 9
}
###
PUT http://localhost:9001/api/demo/003
Content-Type: application/json

{
  "demoId": "001",
  "name": "aaa",
  "value": 9
}
###
PUT http://localhost:9001/api/demo/004
Content-Type: application/json

{
  "demoId": "001",
  "name": "aaa",
  "value": 9
}
###
PUT http://localhost:9001/api/demo/005
Content-Type: application/json

{
  "demoId": "001",
  "name": "aaa",
  "value": 9
}
###